---
- hosts: all
  roles:
  - { role: base, tags: [ 'base' ] }

- hosts: all
  remote_user: root
  roles:
    - { role: gluster, tags: [ 'glusterfs_nodes' ] }


- hosts: all
  remote_user: root
  roles:
    - { role: k8s_node, tags: [ 'k8s_node' ] }

