---
# tasks file for node_add
- name: node add
  template: src=node_add.sh.j2 dest=/tmp/node_add.sh owner=root group=root mode=0755
  when: inventory_hostname in groups['glusterfs_nodes'][0] and ansible_os_family == "RedHat"
  tag: brick_add

- name: sh node.sh
  shell: sh node_add.sh
  when: inventory_hostname in groups['glusterfs_nodes'][0] and ansible_os_family == "RedHat"
  tag: brick_add


- name: brick add
  template: src=brick_add.sh.j2 dest=/tmp/brick_add.sh owner=root group=root mode=0755
  when: inventory_hostname in groups['glusterfs_nodes'][0] and ansible_os_family == "RedHat"
  tag: brick_add

- name: sh brick.sh
  shell: sh brick_add.sh
  when: inventory_hostname in groups['glusterfs_nodes'][0] and ansible_os_family == "RedHat"
  tag: brick_add

